language: node_js

node_js:
  - "4"
  - "6"

# Use container-based Travis infrastructure.
sudo: false

branches:
  only:
    - master
    - /^greenkeeper-.*$/

before_install:
  # GUI for real browsers.
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - yarn run check-cov
  - node_modules/.bin/nyc report --reporter=text-lcov > coverage.lcov && node_modules/.bin/codecov || echo "Codecov upload failed"

  - yarn run build
