// flow-typed signature: a4b22fd2c18369c715c6f11b7232e400
// flow-typed version: <<STUB>>/babel-preset-stage-2_v^6.11.0/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-preset-stage-2'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-preset-stage-2' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-preset-stage-2/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-preset-stage-2/lib/index.js' {
  declare module.exports: $Exports<'babel-preset-stage-2/lib/index'>;
}
