// flow-typed signature: 0a7ecc0a5d33cb6f8953e14a1aa4b897
// flow-typed version: <<STUB>>/builder_v^3.1.0/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'builder'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'builder' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'builder/bin/builder-core' {
  declare module.exports: any;
}

declare module 'builder/bin/builder' {
  declare module.exports: any;
}

declare module 'builder/lib/args' {
  declare module.exports: any;
}

declare module 'builder/lib/config' {
  declare module.exports: any;
}

declare module 'builder/lib/environment' {
  declare module.exports: any;
}

declare module 'builder/lib/log' {
  declare module.exports: any;
}

declare module 'builder/lib/runner' {
  declare module.exports: any;
}

declare module 'builder/lib/spawn' {
  declare module.exports: any;
}

declare module 'builder/lib/task' {
  declare module.exports: any;
}

declare module 'builder/lib/utils/archetype' {
  declare module.exports: any;
}

declare module 'builder/lib/utils/clone' {
  declare module.exports: any;
}

declare module 'builder/lib/utils/json' {
  declare module.exports: any;
}

declare module 'builder/lib/utils/tracker' {
  declare module.exports: any;
}

// Filename aliases
declare module 'builder/bin/builder-core.js' {
  declare module.exports: $Exports<'builder/bin/builder-core'>;
}
declare module 'builder/bin/builder.js' {
  declare module.exports: $Exports<'builder/bin/builder'>;
}
declare module 'builder/lib/args.js' {
  declare module.exports: $Exports<'builder/lib/args'>;
}
declare module 'builder/lib/config.js' {
  declare module.exports: $Exports<'builder/lib/config'>;
}
declare module 'builder/lib/environment.js' {
  declare module.exports: $Exports<'builder/lib/environment'>;
}
declare module 'builder/lib/log.js' {
  declare module.exports: $Exports<'builder/lib/log'>;
}
declare module 'builder/lib/runner.js' {
  declare module.exports: $Exports<'builder/lib/runner'>;
}
declare module 'builder/lib/spawn.js' {
  declare module.exports: $Exports<'builder/lib/spawn'>;
}
declare module 'builder/lib/task.js' {
  declare module.exports: $Exports<'builder/lib/task'>;
}
declare module 'builder/lib/utils/archetype.js' {
  declare module.exports: $Exports<'builder/lib/utils/archetype'>;
}
declare module 'builder/lib/utils/clone.js' {
  declare module.exports: $Exports<'builder/lib/utils/clone'>;
}
declare module 'builder/lib/utils/json.js' {
  declare module.exports: $Exports<'builder/lib/utils/json'>;
}
declare module 'builder/lib/utils/tracker.js' {
  declare module.exports: $Exports<'builder/lib/utils/tracker'>;
}
