// flow-typed signature: 328a10cd891c36d9d2f96ff53fae27c2
// flow-typed version: <<STUB>>/ent_v^2.2.0/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ent'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'ent' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ent/decode' {
  declare module.exports: any;
}

declare module 'ent/encode' {
  declare module.exports: any;
}

declare module 'ent/examples/simple' {
  declare module.exports: any;
}

declare module 'ent/test/codes' {
  declare module.exports: any;
}

declare module 'ent/test/hex' {
  declare module.exports: any;
}

declare module 'ent/test/num' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ent/decode.js' {
  declare module.exports: $Exports<'ent/decode'>;
}
declare module 'ent/encode.js' {
  declare module.exports: $Exports<'ent/encode'>;
}
declare module 'ent/examples/simple.js' {
  declare module.exports: $Exports<'ent/examples/simple'>;
}
declare module 'ent/index' {
  declare module.exports: $Exports<'ent'>;
}
declare module 'ent/index.js' {
  declare module.exports: $Exports<'ent'>;
}
declare module 'ent/test/codes.js' {
  declare module.exports: $Exports<'ent/test/codes'>;
}
declare module 'ent/test/hex.js' {
  declare module.exports: $Exports<'ent/test/hex'>;
}
declare module 'ent/test/num.js' {
  declare module.exports: $Exports<'ent/test/num'>;
}
