// flow-typed signature: b22688a046cd0d2d1ef49c50759b6faf
// flow-typed version: <<STUB>>/history_v^4.4.1/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'history'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'history' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'history/createBrowserHistory' {
  declare module.exports: any;
}

declare module 'history/createHashHistory' {
  declare module.exports: any;
}

declare module 'history/createMemoryHistory' {
  declare module.exports: any;
}

declare module 'history/createTransitionManager' {
  declare module.exports: any;
}

declare module 'history/DOMUtils' {
  declare module.exports: any;
}

declare module 'history/ExecutionEnvironment' {
  declare module.exports: any;
}

declare module 'history/LocationUtils' {
  declare module.exports: any;
}

declare module 'history/PathUtils' {
  declare module.exports: any;
}

declare module 'history/umd/history' {
  declare module.exports: any;
}

declare module 'history/umd/history.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'history/createBrowserHistory.js' {
  declare module.exports: $Exports<'history/createBrowserHistory'>;
}
declare module 'history/createHashHistory.js' {
  declare module.exports: $Exports<'history/createHashHistory'>;
}
declare module 'history/createMemoryHistory.js' {
  declare module.exports: $Exports<'history/createMemoryHistory'>;
}
declare module 'history/createTransitionManager.js' {
  declare module.exports: $Exports<'history/createTransitionManager'>;
}
declare module 'history/DOMUtils.js' {
  declare module.exports: $Exports<'history/DOMUtils'>;
}
declare module 'history/ExecutionEnvironment.js' {
  declare module.exports: $Exports<'history/ExecutionEnvironment'>;
}
declare module 'history/index' {
  declare module.exports: $Exports<'history'>;
}
declare module 'history/index.js' {
  declare module.exports: $Exports<'history'>;
}
declare module 'history/LocationUtils.js' {
  declare module.exports: $Exports<'history/LocationUtils'>;
}
declare module 'history/PathUtils.js' {
  declare module.exports: $Exports<'history/PathUtils'>;
}
declare module 'history/umd/history.js' {
  declare module.exports: $Exports<'history/umd/history'>;
}
declare module 'history/umd/history.min.js' {
  declare module.exports: $Exports<'history/umd/history.min'>;
}
