// flow-typed signature: 47f2cde191583d172722f988e0989cd3
// flow-typed version: <<STUB>>/lodash.assign_v^4.2.0/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lodash.assign'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lodash.assign' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'lodash.assign/index' {
  declare module.exports: $Exports<'lodash.assign'>;
}
declare module 'lodash.assign/index.js' {
  declare module.exports: $Exports<'lodash.assign'>;
}
