// flow-typed signature: a799de9ba38802b283fa8afa334ae8ec
// flow-typed version: <<STUB>>/lodash.chunk_v^4.2.0/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lodash.chunk'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'lodash.chunk' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'lodash.chunk/index' {
  declare module.exports: $Exports<'lodash.chunk'>;
}
declare module 'lodash.chunk/index.js' {
  declare module.exports: $Exports<'lodash.chunk'>;
}
