// flow-typed signature: 297236ab695495c10cff80bebcbb20e7
// flow-typed version: <<STUB>>/redux-loop_v^2.2.2/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-loop'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-loop' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-loop/lib/combineReducers' {
  declare module.exports: any;
}

declare module 'redux-loop/lib/effects' {
  declare module.exports: any;
}

declare module 'redux-loop/lib/errors' {
  declare module.exports: any;
}

declare module 'redux-loop/lib/index' {
  declare module.exports: any;
}

declare module 'redux-loop/lib/install' {
  declare module.exports: any;
}

declare module 'redux-loop/lib/loop' {
  declare module.exports: any;
}

declare module 'redux-loop/lib/utils' {
  declare module.exports: any;
}

declare module 'redux-loop/modules/combineReducers' {
  declare module.exports: any;
}

declare module 'redux-loop/modules/effects' {
  declare module.exports: any;
}

declare module 'redux-loop/modules/errors' {
  declare module.exports: any;
}

declare module 'redux-loop/modules/index' {
  declare module.exports: any;
}

declare module 'redux-loop/modules/install' {
  declare module.exports: any;
}

declare module 'redux-loop/modules/loop' {
  declare module.exports: any;
}

declare module 'redux-loop/modules/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-loop/lib/combineReducers.js' {
  declare module.exports: $Exports<'redux-loop/lib/combineReducers'>;
}
declare module 'redux-loop/lib/effects.js' {
  declare module.exports: $Exports<'redux-loop/lib/effects'>;
}
declare module 'redux-loop/lib/errors.js' {
  declare module.exports: $Exports<'redux-loop/lib/errors'>;
}
declare module 'redux-loop/lib/index.js' {
  declare module.exports: $Exports<'redux-loop/lib/index'>;
}
declare module 'redux-loop/lib/install.js' {
  declare module.exports: $Exports<'redux-loop/lib/install'>;
}
declare module 'redux-loop/lib/loop.js' {
  declare module.exports: $Exports<'redux-loop/lib/loop'>;
}
declare module 'redux-loop/lib/utils.js' {
  declare module.exports: $Exports<'redux-loop/lib/utils'>;
}
declare module 'redux-loop/modules/combineReducers.js' {
  declare module.exports: $Exports<'redux-loop/modules/combineReducers'>;
}
declare module 'redux-loop/modules/effects.js' {
  declare module.exports: $Exports<'redux-loop/modules/effects'>;
}
declare module 'redux-loop/modules/errors.js' {
  declare module.exports: $Exports<'redux-loop/modules/errors'>;
}
declare module 'redux-loop/modules/index.js' {
  declare module.exports: $Exports<'redux-loop/modules/index'>;
}
declare module 'redux-loop/modules/install.js' {
  declare module.exports: $Exports<'redux-loop/modules/install'>;
}
declare module 'redux-loop/modules/loop.js' {
  declare module.exports: $Exports<'redux-loop/modules/loop'>;
}
declare module 'redux-loop/modules/utils.js' {
  declare module.exports: $Exports<'redux-loop/modules/utils'>;
}
