// flow-typed signature: 9e60f721fb3fcdd735404ace953c3029
// flow-typed version: <<STUB>>/url-pattern_v^1.0.3/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'url-pattern'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'url-pattern' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'url-pattern/lib/url-pattern' {
  declare module.exports: any;
}

// Filename aliases
declare module 'url-pattern/lib/url-pattern.js' {
  declare module.exports: $Exports<'url-pattern/lib/url-pattern'>;
}
