// flow-typed signature: 04c9d33ae7c99c8a4deafe0947e6a9f4
// flow-typed version: <<STUB>>/watch_v^1.0.1/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'watch'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'watch' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'watch/cli' {
  declare module.exports: any;
}

declare module 'watch/main' {
  declare module.exports: any;
}

declare module 'watch/test/test_monitor' {
  declare module.exports: any;
}

declare module 'watch/test/test_monitorRootDirectory' {
  declare module.exports: any;
}

declare module 'watch/test/test_watchTree' {
  declare module.exports: any;
}

// Filename aliases
declare module 'watch/cli.js' {
  declare module.exports: $Exports<'watch/cli'>;
}
declare module 'watch/main.js' {
  declare module.exports: $Exports<'watch/main'>;
}
declare module 'watch/test/test_monitor.js' {
  declare module.exports: $Exports<'watch/test/test_monitor'>;
}
declare module 'watch/test/test_monitorRootDirectory.js' {
  declare module.exports: $Exports<'watch/test/test_monitorRootDirectory'>;
}
declare module 'watch/test/test_watchTree.js' {
  declare module.exports: $Exports<'watch/test/test_watchTree'>;
}
