// flow-typed signature: 7d30d82da065e74fbdac92175705af87
// flow-typed version: <<STUB>>/webpack-combine-loaders_v^2.0.3/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webpack-combine-loaders'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'webpack-combine-loaders' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'webpack-combine-loaders/combineLoaders' {
  declare module.exports: any;
}

declare module 'webpack-combine-loaders/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'webpack-combine-loaders/combineLoaders.js' {
  declare module.exports: $Exports<'webpack-combine-loaders/combineLoaders'>;
}
declare module 'webpack-combine-loaders/test/test.js' {
  declare module.exports: $Exports<'webpack-combine-loaders/test/test'>;
}
