// flow-typed signature: 20e530757fed694687def8e0854ccc56
// flow-typed version: <<STUB>>/webpack-partial_v^2.0.2/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webpack-partial'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'webpack-partial' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'webpack-partial/alias' {
  declare module.exports: any;
}

declare module 'webpack-partial/entry' {
  declare module.exports: any;
}

declare module 'webpack-partial/inject' {
  declare module.exports: any;
}

declare module 'webpack-partial/loader' {
  declare module.exports: any;
}

declare module 'webpack-partial/merge' {
  declare module.exports: any;
}

declare module 'webpack-partial/output' {
  declare module.exports: any;
}

declare module 'webpack-partial/partial' {
  declare module.exports: any;
}

declare module 'webpack-partial/plugin' {
  declare module.exports: any;
}

declare module 'webpack-partial/root' {
  declare module.exports: any;
}

declare module 'webpack-partial/tap' {
  declare module.exports: any;
}

// Filename aliases
declare module 'webpack-partial/alias.js' {
  declare module.exports: $Exports<'webpack-partial/alias'>;
}
declare module 'webpack-partial/entry.js' {
  declare module.exports: $Exports<'webpack-partial/entry'>;
}
declare module 'webpack-partial/index' {
  declare module.exports: $Exports<'webpack-partial'>;
}
declare module 'webpack-partial/index.js' {
  declare module.exports: $Exports<'webpack-partial'>;
}
declare module 'webpack-partial/inject.js' {
  declare module.exports: $Exports<'webpack-partial/inject'>;
}
declare module 'webpack-partial/loader.js' {
  declare module.exports: $Exports<'webpack-partial/loader'>;
}
declare module 'webpack-partial/merge.js' {
  declare module.exports: $Exports<'webpack-partial/merge'>;
}
declare module 'webpack-partial/output.js' {
  declare module.exports: $Exports<'webpack-partial/output'>;
}
declare module 'webpack-partial/partial.js' {
  declare module.exports: $Exports<'webpack-partial/partial'>;
}
declare module 'webpack-partial/plugin.js' {
  declare module.exports: $Exports<'webpack-partial/plugin'>;
}
declare module 'webpack-partial/root.js' {
  declare module.exports: $Exports<'webpack-partial/root'>;
}
declare module 'webpack-partial/tap.js' {
  declare module.exports: $Exports<'webpack-partial/tap'>;
}
